"""
Discussion Digest Formatter Utility for Team Ops Assistant.
Turns raw notes or sliding window context into formatted meeting minutes.
"""

import argparse
import datetime
import os
import sys


def format_digest(title: str, topic: str, content: str, output_path: str = None) -> str:
    today = datetime.date.today().strftime("%Y-%m-%d")
    template = f"""# {title}

**Date**: {today}  
**Topic**: {topic}  

---

### 📝 Discussion Summary
{content.strip()}

---
*Generated by GroupConnect Team Ops Assistant at {datetime.datetime.now().strftime('%H:%M:%S')}*
"""
    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(template)
        print(f"Digest saved to: {output_path}")

    return template


def main():
    parser = argparse.ArgumentParser(description="Format discussion digest for team meetings")
    parser.add_argument("--title", default="Discussion Digest", help="Digest Title")
    parser.add_argument("--topic", default="Team Sync", help="Discussion Topic")
    parser.add_argument("--notes", help="Path to raw notes file")
    parser.add_argument("--output", help="Output Markdown file path")
    args = parser.parse_args()

    content = ""
    if args.notes and os.path.exists(args.notes):
        with open(args.notes, "r", encoding="utf-8") as f:
            content = f.read()
    else:
        content = sys.stdin.read()

    result = format_digest(args.title, args.topic, content, args.output)
    if not args.output:
        print(result)


if __name__ == "__main__":
    main()
